project:
  type: website

website:
  navbar:
    title: false
    search: false
    logo: "/images/Untitled.png"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - publications.qmd
    tools:
      - icon: twitter
        href: 
      - icon: github
        href: https://github.com/MPomaville
      - icon: linkedin
        href: https://www.linkedin.com/in/matt-p-109986b7/

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

