project:
  type: website

website:
  navbar:
    title: false
    search: false
    logo: "/images/Untitled.png"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - resume.qmd
      - publications.qmd

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

